### ISSUE TITLE
package not found

### ISSUE THREAD

**Issue by weikaishio** [huajiao-tv/gokeeper#1]
1. repository 'https://github.com/qmessenger/utility/' not found
2. build github.com/huajiao-tv/gokeeper/example/mycomponent: cannot load github.com/huajiao-tv/gokeeper/example/mycomponent/data: cannot find module providing package github.com/huajiao-tv/gokeeper/example/mycomponent/data

**Comment by youlu-cn** [comment]
@overstep123

**Comment by overstep123** [comment]
Thank you for your proposal,we have fixed.
